export type PaladiumStatus =
  | 'online'
  | 'offline'
  | 'maintenance'
  | 'running'
  | 'starting'
  | 'restarting'
  | 'stopping'
  | 'unknown'
  | 'whitelist'

export type Job = 'alchemist' | 'farmer' | 'hunter' | 'miner'

export type Rank =
  | 'default'
  | 'titan'
  | 'paladin'
  | 'endium'
  | 'divinity'
  | 'legende'
  | 'legend'
  | 'heros'
  | 'trixium'
  | 'trixium+'
  | 'premium'
  | 'rusher'
  | 'youtuber'
  | 'streamer'
  | 'helper'
  | 'supportconfirmé'
  | 'moderateurchat'
  | 'moderateur'
  | 'moderateursenior'
  | 'operateur'
  | 'operateurcertif'
  | 'operateursenior'
  | 'paladium-staff'
  | 'discord'
  | 'discord+'
  | 'graphistejunior'
  | 'graphiste'
  | 'création'
  | 'redacteur'
  | 'gamedesigner'
  | 'developpeurjunior'
  | 'developpeur'
  | 'developpeursenior'
  | 'graphistesenior'
  | 'responsable'
  | 'administrateur'
