FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y \
    chromium \
    xvfb \
    unclutter \
    ffmpeg \
    --no-install-recommends && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY start.sh /start.sh
RUN chmod +x /start.sh

EXPOSE 9222

CMD ["/start.sh"]
